version: '3.7'

networks:
  traefik:
    name: traefik

services:
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    networks:
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.port=80"

      # Define the URL to access this app
      - "traefik.http.routers.whoami.rule=Host(`whoami2.${DOMAINNAME}`)"

      # Access via HTTPS only
      - "traefik.http.routers.whoami.entrypoints=websecure"

      # Forward authentication to keycloak for logon
      - "traefik.http.routers.whoami.middlewares=keycloakForwardAuth@docker"
      
      # The application (i.e. this container)
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

      # TLS is used to protect the domain
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=basic"
      - "traefik.http.routers.whoami.tls.domains[0].main=${DOMAINNAME}"
      - "traefik.http.routers.whoami.tls.domains[0].sans=*.${DOMAINNAME}"
